### ISSUE TITLE
[ XDMoD 6.5.0 Centos 7.3 ] Admin User

### ISSUE THREAD

**Issue by dspatil7768** [ubccr/xdmod#111]
Can I reset admin user? Actually, I forgot the password for admin user. I tried changing it in MySQL but still it is not accepting. 

`mqsql> UPDATE moddb.Users SET Password=PASSWORD("new_pass") WHERE Username='admin'`

Even I'm trying in `xdmod-setup` to setup admin user it is showing that admin user is already there.

What should I do?

**Comment by jtpalmer** [comment]
Try this in MySQL:

```sql
UPDATE moddb.Users SET password = MD5('new_pass') WHERE username = 'admin';
```

Note the use of `MD5` instead of `PASSWORD`.

**Comment by dspatil7768** [comment]
Thank you. Worked fine👍
