### ISSUE TITLE
XDMoD shredder fails with MySQL 5.7.5+

### ISSUE THREAD

**Issue by Samathy** [ubccr/xdmod#125]
Due to the change in behavior of the SQL GROUP BY clause XDMoD's shredder fails on MySQL Versions 5.7.5 upwards.

## Expected Behavior
The Shredder should succeed and import shredded logs into the MySQL database.

## Current Behavior
The shredder fails to write to the database with the error:

    SELECT list is not in GROUP BY clause and contains nonaggregated column 'mod_shredder.shredded_job_sge.job_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

## Possible Solution
As suggested in the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html) disabling ONLY_FULL_GROUP_BY fixes the issue.
Disabling ONLY_FULL_GROUP_BY can be done by removing the clause from the 'sql_mode' global variables list.

The following command sets the global variable 'sql_mode' to all the defaults in MySQL 5.7.18 *omitting* ONLY_FULL_GROUP_BY.

    set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

Default values for 'sql_mode' can be found by running:

    SHOW VARIABLES LIKE 'sql_mode'

This is probably not an ideal long term solution though.

## Steps to Reproduce (for bugs)
1. Install MySQL 5.7.5+ (Default for Ubuntu 16.04 is 5.7.18)
2. Run xdmod-shredder -f sge -i [FILE]

## Context
Cannot shred existing logs into the database on Ubuntu 16.04 using the version of MySQL shipped with Ubuntu 16.04.

## Your Environment
* Version used: XDMoD 6.6
* Environment name and version (e.g. Chrome 39, Node.js 5.4): MySQL 5.7.18, PHP 7.1
* Operating system and version (desktop or mobile): Ubuntu 16.04

**Comment by iotaka** [comment]
Hello with MariaDB 10 (available in ubuntu repos) there it is the same problem?

**Comment by jtpalmer** [comment]
Newer versions of MySQL and MariaDB have changed the default SQL mode.  Unfortunately, Open XDMoD will not work with these settings, so you will need to the `sql_mode` setting.  We have used both MySQL 5.1, 5.5 and MariaDB 5.5 with `sql_mode=''`.  I haven't tested any other versions, but will I will try those available in Ubuntu 16.04 to see if they work.

For reference, here is the SQL mode documentation:

- https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html
- https://mariadb.com/kb/en/mariadb/sql-mode/

**Comment by iotaka** [comment]
MariaDB changed the default values of `sql_mode` various time.

From the doc:

> The session value only affects the current client, and can be changed by the client when required. 

So you can set it properly in you code.

You can install the last MariaDB (for all versions from 5.5 to 10.3) from they official repos:
https://downloads.mariadb.org/mariadb/repositories/


In  MariaDB 10.2.6 I have:
```SHOW VARIABLES LIKE 'sql_mode';
+---------------+-------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                     |
+---------------+-------------------------------------------------------------------------------------------+
| sql_mode      | STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------+```

so there is no ONLY_FULL_GROUP_BY and seems that only MySQL > 5.7.5 uses it, not MariaDB.

**Comment by jtpalmer** [comment]
@iotaka Are you experiencing any issues with the `GROUP BY` queries, or just what you've described in #172

**Comment by iotaka** [comment]
@jtpalmer only what I'm describing in  #172
