### ISSUE TITLE
XDMoD 6.6 gives blank page on Ubuntu 16.04 instead of expected web interface.

### ISSUE THREAD

**Issue by Samathy** [ubccr/xdmod#129]
After shredding and ingesting data successfully, XDMoD's web interface is a blank page. 

## Expected Behavior
XDMoD should show the default web interface.

## Current Behavior
XDMoD's web interface does not show. Instead, Firefox shows a blank webpage with basically no HTML content:

    <html>
        <head> </head>
        <body> </body>
    </html>

On further research I discovered that index.php:84 appears not to return at all. (that line's code is below)

    $user = XDUser::getPublicUser();

Adding a call to print below the line doesn't ever output anything.

Commenting that line out and replacing it with a call to the default constructor of XDUser results in some JSON appearing on the webpage. The same result is achieved by making the '$user' variable equal to an empty string.

The webpage with the JSON has lots of '<meta>', '<script>' and '<link>' tags in the HTML '<head>' consistent with index.php.

index.php:84 replacement:

    $user = ""
    OR
    $user = XDUser();

Resulting output:

    {"success": false, "count": 0, "total":0, "totalCount":0, "results":[], "data":[], "message",{}}

## Steps to Reproduce (for bugs)
1. Build and Install XDMoD 6.6 as per [instructions](http://open.xdmod.org/install-source.html) on Ubuntu 16.04
2. Shred and ingest some data
3. Open web interface in Firefox.

## Context
Attempting to install XDMoD on Ubuntu 16.04 to test new functionality.

## Your Environment
* Version used: XDMoD 6.6
* Environment name and version (e.g. Chrome 39, Node.js 5.4): Firefox 53, PHP 7.1
* Operating system and version (desktop or mobile): Ubuntu 16.04 desktop.

**Comment by jtpalmer** [comment]
I haven't been able to reproduce what you described.  Are you seeing any errors in the Apache logs or in the Open XDMoD logs (exceptions.log, etc.)?

I installed the default version of PHP from the Ubuntu 16.04 repositories and only have version 7.0:

```
$ php --version
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

You listed PHP 7.1, did you install those packages from somewhere else?

**Comment by jtpalmer** [comment]
@Samathy are you still having this issue?  Let us know if you find anything else that you think is causing the problem.

**Comment by Samathy** [comment]
Hi @jtpalmer, 
Sorry for the delay, I've been working on other projects. 
Turns out I was using PHP 7.1 from a ppa as opposed to the 7.0 from the default repos.
Switching to 7.0 solved this issue right away.
The interface shows as expected.

You can close this if theres no more questions.

**Comment by jtpalmer** [comment]
Thank you for your feedback.  We're still working on improving compatibility with PHP 7.0+ so let us know if you run into any other issues.
