### ISSUE TITLE
sender_email preference not used when sending reports

### ISSUE THREAD

**Issue by olivierh65** [ubccr/xdmod#171]
When sending reports, the sender is always xdmod-bounces@ccr.buffalo.edu.
This value is hard coded in classes/ZendMailWrapper.php

## Possible Solution
Modify classes/ZendMailWrapper.php to :

        require_once 'Zend/Mail.php';
       # Get sendar_email preference value
       $mailer_sender = xd_utilities\getConfiguration('mailer', 'sender_email');
        $tr = new Zend_Mail_Transport_Sendmail(
       # Use the email_sender
        "-f$mailer_sender"
        );

## Your Environment
* Version used: XDModD 6.6.0

**Comment by plessbd** [comment]
this will be addressed by #158
