### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by iotaka** [ubccr/xdmod#172]
Hello,

with xdmod 6.6 on a centos 7.3 with MariaDB 10.2.6 I receive the following parsing errors:

```2017-06-27 16:50:07 [critical] Failed to shred files: Failed to shred line 16130 of file /var/xdmod/compute.dat "short:n0015:localusers:80001180:impi-test:20095:sge:0:1302531315:1302531315:1302531321:0:0:6:0.320951:0.089986:0.000000:0:0:0:0:23394:2:0:0.000000:0:0:0:0:641:130:NONE:defaultdepartment:impi:12:0:0.410937:0.000000:0.000000:-q short@n0015 -pe impi 12:0.000000:1.n0015:0.000000:0:0": SQLSTATE[01000]: Warning: 1265 Data truncated for column 'pe_taskid' at row 1 (stacktrace: #0 /usr/bin/xdmod-shredder(209): OpenXdmod\Shredder->shredFile('/var/xdmod/comp...')```

this is the RAW line

```short:n0015:localusers:80001180:impi-test:20095:sge:0:1302531315:1302531315:1302531321:0:0:6:0.320951:0.089986:0.000000:0:0:0:0:23394:2:0:0.000000:0:0:0:0:641:130:NONE:defaultdepartment:impi:12:0:0.410937:0.000000:0.000000:-q short@n0015 -pe impi 12:0.000000:1.n0015:0.000000:0:0```

I check in the DB and  pe_taskid it is an INT so **1.n0015** it is a problem.

`SHOW COLUMNS FROM shredded_job_sge;`

`| pe_taskid                      | int(11)             | YES  |     | NULL    |                |`

In the 99,9% I see a NONE value for the pe_taskid in my logs so NULL in the DB.

I have also this one:

``` 2017-06-27 17:05:33 [critical] Failed to shred files: Failed to shred line 1844 of file /var/xdmod/bd.dat "gstinf:n0051:usersch:50000058:static_freq_blade_scaledtoS6:453797:sge:0:1469625909:1469625912:1469735919:0:0:110007:441110.841959:11505.274932:239503848.000000:0:0:0:0:358442710:1324577:0:5388119304.000000:1438757160:0:0:0:107133840:51436055:NONE:defaultdepartment:abaqus-smp:8:0:452616.116891:955584.514198:47225.233569:-U usersch -q gstinf -l abaqus=12 -pe abaqus-smp 8:0.000000:NONE:6017945600.000000:0:0": SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'ru_inblock' at row 1 (stacktrace: #0 /usr/bin/xdmod-shredder(209): OpenXdmod\Shredder->shredFile('/var/xdmod/bade...')```

Thank you.

**Comment by jtpalmer** [comment]
Which database were you using when you received these errors?  The first error is just a warning, so there is probably some database setting that is making these warnings into errors.  If you can disable the warnings, this might not be a serious issue, since we currently aren't using either of those columns.  That said, I'll put together a pull request to change the database columns to prevent issues in the future.

Also, what version/variant of SGE are you using?

**Comment by iotaka** [comment]
hi @jtpalmer 

GE 6.2u5

**Comment by iotaka** [comment]
I have also this errors during the ingestion:
```2017-06-28 11:17:57 [error] Command returned non-zero value '1': ERROR 1366 (22007) at line 1: Incorrect integer value: '' for column 'job_array_index' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
#1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
#2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
#3 /usr/bin/xdmod-shredder(241): PDODBMultiIngestor->ingest()
#4 /usr/bin/xdmod-shredder(22): main()
#5 {main}, statement: load data local infile '/tmp/shredded_job.data.3306.hYA3Iy' replace into table shredded_job fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (date_key,job_id,job_array_index,job_name,resource_name,queue_name,user_name,group_name,account_name,project_name,pi_name,start_time,end_time,submission_time,wall_time,wait_time,node_count,cpu_count,source_format))
2017-06-28 11:17:58 [error] Command returned non-zero value '1': ERROR 1366 (22007) at line 1: Incorrect integer value: '' for column 'id' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
#1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
#2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
#3 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(373): PDODBMultiIngestor->ingest()
#4 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(337): OpenXdmod\DataWarehouseInitializer->ingest(Array, Object(CCR\DB\MySQLDB), Object(CCR\DB\MySQLDB), NULL, NULL)
#5 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(239): OpenXdmod\DataWarehouseInitializer->ingestAllHpcdb(NULL, NULL)
#6 /usr/bin/xdmod-ingestor(227): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
#7 /usr/bin/xdmod-ingestor(21): main()
#8 {main}, statement: load data local infile '/tmp/resourcetype.data.3306.G3SC1C' replace into table resourcetype fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (id,abbrev,description))
```

```
select count(*) from shredded_job;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

Seems that nothing is insert in the DB during the Shredder phase, after the error posted above `xdmod-shredder` don't go further. The insert in the DB is done after parse the whole file by `xdmod-shredder`?

Thank you.

**Comment by jtpalmer** [comment]
For the first problem you found, there are several columns in `mod_shredder.shredded_job_sge` are the incorrect type.  You can alter them with this:

```sql
USE mod_shredder;
ALTER TABLE `shredded_job_sge`
    MODIFY COLUMN `maxvmem` decimal(32,6) DEFAULT NULL,
    MODIFY COLUMN `pe_taskid` varchar(255) DEFAULT NULL,
    MODIFY COLUMN `ru_inblock` decimal(32,6) DEFAULT NULL,
    MODIFY COLUMN `ru_maxrss` decimal(32,6) DEFAULT NULL,
    MODIFY COLUMN `ru_stime` decimal(32,6) DEFAULT NULL,
    MODIFY COLUMN `ru_utime` decimal(32,6) DEFAULT NULL;
```

If you have any suggestions of documentation regarding the proper types and size limits of these values, please let us know.

Another work-around would be to remove `STRICT_TRANS_TABLES` from the `sql_mode`.  I see your suggestion in #125 that Open XDMoD should change the `sql_mode`, so I'll look into that as well.

**Comment by iotaka** [comment]
Hello @jtpalmer 

after do the alter table it worked a lot more. Now I have the followings errors:


I have thousand of this:
```
2017-06-29 09:44:03 [error] Failed to correct job times (start_time: 0, end_time: 0, walltime: 0)
```
^ I remember to always had this type of errors also with old version and on other systems. Do you have any idea about this?



3 of this:
```
2017-06-29 09:41:51 [error] Command returned non-zero value '1': ERROR 1366 (22007) at line 1: Incorrect integer value: '' for column 'job_array_index' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
#1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
#2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
#3 /usr/bin/xdmod-shredder(241): PDODBMultiIngestor->ingest()
#4 /usr/bin/xdmod-shredder(22): main()
#5 {main}, statement: load data local infile '/tmp/shredded_job.data.3306.JQAXjU' replace into table shredded_job fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (date_key,job_id,job_array_index,job_name,resource_name,queue_name,user_name,group_name,account_name,project_name,pi_name,start_time,end_time,submission_time,wall_time,wait_time,node_count,cpu_count,source_format))
```


this one
```
2017-06-29 09:44:03 [error] Failed to correct job times (start_time: sge, end_time: 0, walltime: 1490016904)
2017-06-29 09:44:09 [critical] Failed to shred files: Failed to shred line 458730 of file /var/xdmod/compute.dat "long:n0006:usersch:vgl:vgl0:aeroturb:00005882:fluent-post:579398:sge:0:1490016710:1490016710:1490016904:0:0:194:0.019996:0.013997:3808.000000:0:0:0:0:1982:0:0:0.000000:8:0:0:0:56:11:NONE:defaultdepartment:NONE:1:0:0.033993:0.000000:0.000000:-U aeroturb -q vgl -I y:0.000000:NONE:0.000000:0:0": SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'aeroturb' for column 'job_number' at row 1 (stacktrace: #0 /usr/bin/xdmod-shredder(209): OpenXdmod\Shredder->shredFile('/var/xdmod/comp...')
#1 /usr/bin/xdmod-shredder(22): main()
#2 {main})
```


and this one, so some errors above cause the fail of the ingestion
```
017-06-29 09:44:13 [error] Command returned non-zero value '1': ERROR 1366 (22007) at line 1: Incorrect integer value: '' for column 'id' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
#1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
#2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
#3 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(373): PDODBMultiIngestor->ingest()
#4 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(337): OpenXdmod\DataWarehouseInitializer->ingest(Array, Object(CCR\DB\MySQLDB), Object(CCR\DB\MySQLDB), NULL, NULL)
#5 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(239): OpenXdmod\DataWarehouseInitializer->ingestAllHpcdb(NULL, NULL)
#6 /usr/bin/xdmod-ingestor(227): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
#7 /usr/bin/xdmod-ingestor(21): main()
#8 {main}, statement: load data local infile '/tmp/resourcetype.data.3306.pUZvAg' replace into table resourcetype fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (id,abbrev,description))
```

Thank you

**Comment by jtpalmer** [comment]
> I have thousand of this:
>
> ```
> 2017-06-29 09:44:03 [error] Failed to correct job times (start_time: 0, end_time: 0, walltime: 0)
> ```

There isn't much we can do about this.  These are jobs that are missing the start time, end time and walltime (they have zero values).  If you know of some criteria where these can be safely ignored we can add a check for that situation.  I would prefer to not ignore them by default since they could be a sign of a larger problem.  I don't have a good understanding of why Grid Engine is producing these logs with zero values, so any information you can provide would be useful.

> ```
> 2017-06-29 09:44:03 [error] Failed to correct job times (start_time: sge, end_time: 0, walltime: 1490016904)
> 2017-06-29 09:44:09 [critical] Failed to shred files: Failed to shred line 458730 of file /var/xdmod/compute.dat "long:n0006:usersch:vgl:vgl0:aeroturb:00005882:fluent-post:579398:sge:0:1490016710:1490016710:1490016904:0:0:194:0.019996:0.013997:3808.000000:0:0:0:0:1982:0:0:0.000000:8:0:0:0:56:11:NONE:defaultdepartment:NONE:1:0:0.033993:0.000000:0.000000:-U aeroturb -q vgl -I y:0.000000:NONE:0.000000:0:0": SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'aeroturb' for column 'job_number' at row 1 (stacktrace: #0 /usr/bin/xdmod-shredder(209): OpenXdmod\Shredder->shredFile('/var/xdmod/comp...')
> #1 /usr/bin/xdmod-shredder(22): main()
> #2 {main})
> ```

It looks like there are extra fields in this line, or the job name contains colons.  Do you have any other logs where you can verify the name of the job?  If colons are allowed in job names and they are not escaped, it will be difficult to parse lines such as this.

I'm still looking into the issue with that last error.  Please post the contents of your resource_types.json file so I can see if something is missing there.

**Comment by iotaka** [comment]
Hello @jtpalmer it is a log file of 179MB, I can retrieve another of 241MB  from a different cluster and check it with the version 6.6 and see what happen.

usually `qacct -j joib_id` give info, but for the job 579398 nothing, it is an interactive one, so the name is generated by the system (we have a menu entry) and it is _fluent-post_ so there is not a colon in the name.

`resource_types.json`
```json
[
    {
        "id": 1,
        "abbrev": "Default",
        "description": "Default Resource Type"
    }
]
```

Thank you

**Comment by jtpalmer** [comment]
If you run the shredder with the `--debug` flag you can see the parsed data.  If you have any problems with a specific line, copy that to a separate file and shred that file.  Here is what I'm seeing:

```json
{
    "qname": "long",
    "hostname": "n0006",
    "groupname": "usersch",
    "owner": "vgl",
    "job_name": "vgl0",
    "job_number": "aeroturb",
    "account": "00005882",
    "priority": "fluent-post",
    "submission_time": "579398",
    "start_time": "sge",
    "end_time": "0",
    "failed": "1490016710",
    "exit_status": "1490016710",
    "ru_wallclock": "1490016904",
    "ru_utime": "0",
    "ru_stime": "0",
    "ru_maxrss": "194",
    "ru_ixrss": "0.019996",
    "ru_ismrss": "0.013997",
    "ru_idrss": "3808.000000",
    "ru_isrss": "0",
    "ru_minflt": "0",
    "ru_majflt": "0",
    "ru_nswap": "0",
    "ru_inblock": "1982",
    "ru_oublock": "0",
    "ru_msgsnd": "0",
    "ru_msgrcv": "0.000000",
    "ru_nsignals": "8",
    "ru_nvcsw": "0",
    "ru_nivcsw": "0",
    "project": "0",
    "department": "56",
    "granted_pe": "11",
    "slots": "NONE",
    "task_number": "defaultdepartment",
    "cpu": "NONE",
    "mem": "1",
    "io": "0",
    "category": "0.033993",
    "iow": "0.000000",
    "pe_taskid": "0.000000",
    "maxvmem": "-U aeroturb -q vgl -I y",
    "arid": "0.000000",
    "ar_submission_time": "NONE"
}
```

It looks like the fields are shifted by 3.  If the job name is fluent-post, then there is some problem with something before that:

```
long:n0006:usersch:vgl:vgl0:aeroturb:00005882:fluent-post:...
```

The fields before the job name are `qname`, `hostname`, `group`, and `owner`, but there are 7 fields here.  Please check to see if you can confirm the value of any of those fields.  I don't think there is any way to automatically detect problems like this, so you may have to correct or remove the line manually.

**Comment by iotaka** [comment]
For the 
```
[error] Failed to correct job times (start_time: 0, end_time: 0, walltime: 0)
```
it is possible suppress it in quiet mode at least? Also in the other file I have a lot of this.

It possible simply use UTF8 for text fields of the table?


**There is a lot of stuff in the other file**

I have some crap in the group field

```
n0006.q:n0006:°Ïÿ¿^?:brd:test:616:sge:0:1206725904:0:0:28:0:0:0:0:0.000000:0:0:0:0:0:0:0:0.000000:0:0:0:0:0:0:NONE:defaultdepartment:ansys-smp:4:0:0.000000:0.000000:0.000000:-pe ansys-smp 4:0.000000:NONE:0.000000
n0006.q:n0006:°Ïÿ¿^?:brd:test:616:sge:0:1206725904:0:0:28:0:0:0:0:0.000000:0:0:0:0:0:0:0:0.000000:0:0:0:0:0:0:NONE:defaultdepartment:ansys-smp:4:0:0.000000:0.000000:0.000000:-pe ansys-smp 4:0.000000:NONE:0.000000
n0004.q:n0004:°Ïÿ¿^?:brd:test:617:sge:0:1206726484:0:0:28:0:0:0:0:0.000000:0:0:0:0:0:0:0:0.000000:0:0:0:0:0:0:NONE:defaultdepartment:ansys-smp:4:0:0.000000:0.000000:0.000000:-pe ansys-smp 4:0.000000:NONE:0.000000
n0006.q:n0006:°Ïÿ¿^?:brd:test:617:sge:0:1206726484:0:0:28:0:0:0:0:0.000000:0:0:0:0:0:0:0:0.000000:0:0:0:0:0:0:NONE:defaultdepartment:ansys-smp:4:0:0.000000:0.000000:0.000000:-pe ansys-smp 4:0.000000:NONE:0.000000
```

```
PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in /usr/share/xdmod/classes/OpenXdmod/Shredder/Sge.php on line 338
2017-06-29 15:29:25 [error] Failed to correct job times (start_time: 0, end_time: 0, walltime: 0)
2017-06-29 15:29:25 [critical] Failed to shred files: Failed to shred line 612 of file /var/xdmod/accounting "n0006.q:n0006:����:brd:test:616:sge:0:1206725904:0:0:28:0:0:0:0:0.000000:0:0:0:0:0:0:0:0.000000:0:0:0:0:0:0:NONE:defaultdepartment:ansys-smp:4:0:0.000000:0.000000:0.000000:-pe ansys-smp 4:0.000000:NONE:0.000000": SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xB0\xCF\xFF\xBF' for column 'groupname' at row 1 (stacktrace: #0 /usr/bin/xdmod-shredder(209): OpenXdmod\Shredder->shredFile('/var/xdmod/acco...')
#1 /usr/bin/xdmod-shredder(22): main()
#2 {main})
PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in /usr/share/xdmod/classes/Log/xdmdb2.php on line 12
```
This error if fatal and the shrader stops, after deleting the 4 lines above I found also this one:

```
PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in /usr/share/xdmod/classes/OpenXdmod/Shredder/Sge.php on line 338
2017-06-29 15:34:39 [critical] Failed to shred files: Failed to shred line 2663 of file /var/xdmod/accounting "n0026.q:n0026:cfd-tech:dmn:fordKA_14444�:2733:sge:0:1221829472:1221829485:1221829494:100:137:9:0:0:0.000000:0:0:0:0:2322:0:0:0.000000:0:0:0:0:200:10:NONE:defaultdepartment:cfx:32:0:1.600000:0.020093:0.000000:-pe cfx 32:0.000000:NONE:62574592.000000": SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xB0' for column 'job_name' at row 1 (stacktrace: #0 /usr/bin/xdmod-shredder(209): OpenXdmod\Shredder->shredFile('/var/xdmod/acco...')
#1 /usr/bin/xdmod-shredder(22): main()
#2 {main})
PHP Warning:  json_encode(): Invalid UTF-8 sequence in argument in /usr/share/xdmod/classes/Log/xdmdb2.php on line 12
```

the job name is: 'fordKA_14444°' with a degree symbol (on an Italian keyboard it is present)

then crushes on this (after deleting the lines above)

```
2017-06-29 15:44:46 [critical] Failed to shred files: Failed to shred line 353100 of file /var/xdmod/accounting "vgl2.q:vgl2:enginsoft:nrs:mast-test:353668:sge:0:1258561084:1258561086:1258561233:0:0:147:146:0:0.000000:0:0:0:0:11611:15:0:0.000000:0:0:0:0:1256:522:NONE:defaultdepartment:NONE:1:0:146.080000:1.075506:0.000000:-l h_rt=infinity:0.000000:NONE:13447168.000000": SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'infinity' for column 'resource_list_h_rt' at row 1 (stacktrace: #0 /usr/bin/xdmod-shredder(209): OpenXdmod\Shredder->shredFile('/var/xdmod/acco...')
#1 /usr/bin/xdmod-shredder(22): main()
#2 {main})
```

then crushes on this (after deleting the lines above)

job name 'T2_sì_each_mesh_fitta' the ì (on an Italian keyboard it is present)

another group with crap ` ×J<93>ÿ^?` this sure it is an error because every user has **domusers** so it is a non sense, but I found 5 or 6 of it spread in the file.

```
2017-06-29 16:06:40 [error] Expected at least 43 fields, found 5 in line: opteron:n0039:o commproc (qmaster:1) on host "bee.ctn": can't resolve host name
2017-06-29 16:06:40 [error] Expected at least 43 fields, found 41 in line: :v.pri:spaco1804:730207:sge:0:1387359579:1387359658:1387360421:0:0:763:1458:29:186580.000000:0:0:0:0:60391:0:0:0.000000:0:0:0:0:7741:57446:NONE:defaultdepartment:lsdyna-smp:2:0:1487.000000:547.071234:0.000000:-pe lsdyna-smp 2:0.000000:NONE:404721664.000000
```

```
opteron:n0039:o commproc (qmaster:1) on host "bee.ctn": can't resolve host name
:v.pri:spaco1804:730207:sge:0:1387359579:1387359658:1387360421:0:0:763:1458:29:186580.000000:0:0:0:0:60391:0:0:0.000000:0:0:0:0:7741:57446:NONE:defaultdepartment:lsdyna-smp:2:0:1487.000000:547.071234:0.000000:-pe lsdyna-smp 2:0.000000:NONE:404721664.000000
```

**Comment by iotaka** [comment]
`long:n0006:usersch:vgl:vgl0:aeroturb:00005882:fluent-post:`

the first 3 are queue, node and group

then this 3 fields vgl:vgl0:aeroturb that they are 
queue, node and group  and the job name is coherent with this last 3 not with the first 3.

So for me the long:n0006:usersch: it is a line of an interrupted write or something similar, the only things that you can do it is if a line has too arguments skip it

**Comment by iotaka** [comment]
after cleaning all the crappy lines from the file 241MB, I receive only a lot of error] Failed to correct job times 

but the ingestion still fails because the DB it is empty.

**Comment by jtpalmer** [comment]
> For the
>
> ```
> [error] Failed to correct job times (start_time: 0, end_time: 0, walltime: 0)
> ```
> it is possible suppress it in quiet mode at least?

Do you know why you have so many jobs with 0 start and end times?  Were they cancelled before they started?

We could change the log level of that message so they are not errors.

> It possible simply use UTF8 for text fields of the table?

This is something that we plan to do in the future, but I don't know when that change will happen.

> So for me the long:n0006:usersch: it is a line of an interrupted write or something similar, the only things that you can do it is if a line has too arguments skip it

We can't skip lines with too many fields because some of the other SGE variants have added additional fields so the total number of fields is not always the same.

> after cleaning all the crappy lines from the file 241MB, I receive only a lot of Failed to correct job times, but the ingestion still fails because the DB it is empty.

Did you try starting over with an empty database (e.g. run `xdmod-admin --truncate --jobs`)?  Is the table `modw_shredder.shredded_job_sge` empty?

**Comment by iotaka** [comment]
> 
> 
>     For the
> 
>     [error] Failed to correct job times (start_time: 0, end_time: 0, walltime: 0)
> 
>     it is possible suppress it in quiet mode at least?
> 
> Do you know why you have so many jobs with 0 start and end times? Were they cancelled before they started?

They are jobs put in queue A, then after some time the users see that queue B it is free, eh resubimt the job on B and delete the job on A (never started, still queue). It happens on our clusters, it is a normal behavior.

>     It possible simply use UTF8 for text fields of the table?
> 
> This is something that we plan to do in the future, but I don't know when that change will happen.

it is a simply parameter, in not english languages it is a lot common have non ASCII characters ans SGE accepts this names. 

I dropped all the databases (why more than one DB?) and recreate them with xdmod-setup.

I don't have any mod**w**_shredder DB, I have mod_shredder.

```SQL
select count(*) from mod_shredder.shredded_job_sge;
+----------+
| count(*) |
+----------+
|  1011463 |
+----------+
```

**Comment by jtpalmer** [comment]
> I don't have any modw_shredder DB, I have mod_shredder.

Yes, that should have been `mod_shredder` not `modw_shredder`.  Please also check the count in `mod_shredder.shredded_job`.

**Comment by iotaka** [comment]
```SQL
select count(*) from mod_shredder.shredded_job;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

**Comment by jtpalmer** [comment]
This indicates that there was a problem with the shredding process.  You can truncate `shredded_job_sge` and try re-shredding your log files if you think you've solved all the current issues.

**Comment by iotaka** [comment]
> This indicates that there was a problem with the shredding process. You can truncate shredded_job_sge and try re-shredding your log files if you think you've solved all the current issues.

It was I did, the shredder crashes with this error

```
2017-07-03 16:22:42 [error] Command returned non-zero value '1': ERROR 1366 (22007) at line 1: Incorrect integer value: '' for column 'job_array_index' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
#1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
#2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
#3 /usr/bin/xdmod-shredder(241): PDODBMultiIngestor->ingest()
#4 /usr/bin/xdmod-shredder(22): main()
#5 {main}, statement: load data local infile '/tmp/shredded_job.data.3306.FQdAuM' replace into table shredded_job fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (date_key,job_id,job_array_index,job_name,resource_name,queue_name,user_name,group_name,account_name,project_name,pi_name,start_time,end_time,submission_time,wall_time,wait_time,node_count,cpu_count,source_format))
```
Maybe something is missing, or some defaults of mariadb 10.2.6

**Comment by jtpalmer** [comment]
Sorry, I didn't realize you were still having that problem.  The `job_array_index` is taken from the `task_number` which should be an integer.  I have seen problems where zero is converted into the empty string and this may be the case here.  This may be another issue where `sql_mode` is defaulting to something stricter.  Please try setting `sql_mode=''` to see if that resolves the issue.

**Comment by iotaka** [comment]
Currently, sql_mode variable can be set for the mysql server on a GLOBAL level for all of its objects. Also, it can be set dynamically for session/ global level for mysql server.

@jtpalmer can you say to me please where set `sql_mode=''` in your code, because I prefer avoid to change the global default.

**Comment by jtpalmer** [comment]
@iotaka there is no place to set `sql_mode` in the code.  Please change it globally.

**Comment by utkarsh123bholu** [comment]
I have the same error..https://github.com/ubccr/xdmod/issues/61   bug #61 
this is output for SELECT * FROM mod_hpcdb.hpcdb_reso

+---------+-----------+-----------------------+
| type_id | type_abbr | type_desc |
+---------+-----------+-----------------------+
| 0 | UNKNOWN | Unknown resource type |
| 1 | Default | Default Resource Type |
+---------+-----------+-----------------------+
this is output for resources_types.json

[
{
"id": 1,
"abbrev": "Default",
"description": "Default Resource Type"
}
]
help me. I am new to xdmod

**Comment by iotaka** [comment]
@jtpalmer   for me it is very easy to do it in PHP code and it is transparent to the final user.

```php
mysql_query("SET SESSION sql_mode = ''");
```
It is a simply query and it is valid on your connection only.

In any case I tested altering the global parameter for testing purposes. I **don't** receive the error 
`[error] Command returned non-zero value '1'`.

but

```
select count(*) from mod_shredder.shredded_job;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```

instead 

```
select count(*) from mod_shredder.shredded_job_sge;
+----------+
| count(*) |
+----------+
|  1011706 |
+----------+
```

**Comment by jtpalmer** [comment]
@iotaka Thank you for testing with the global change to `sql_mode`.  I understand that it is possible to change this in the PHP code, but we are not doing that at the current time and I don't know if and when we will do that in the future.

Did you truncate mod_shredder.shredded_job_sge before testing again?  I think that will be necessary due to the way new data is shredded/ingested.

**Comment by jtpalmer** [comment]
@utkarsh123bholu Please try setting the global `sql_mode` to `''`.

**Comment by iotaka** [comment]
@jtpalmer  
`xdmod-admin --truncate --jobs` plus working for a lot of time seems work, also the ingestion :)

thank you
