### ISSUE TITLE
Wrong Date on chart

### ISSUE THREAD

**Issue by iotaka** [ubccr/xdmod#179]
## Expected Behavior
Plotting the moth of June I expect to see the data for 1st of June to the 30rd of June. I always had this problem also with old versions ox XDMoD.

## Current Behavior
I see 31st May to 29rd June

![xdmod](https://user-images.githubusercontent.com/11047721/27903704-835a0bdc-623a-11e7-8320-c56ef9eb49ca.png)
_I merged two screenshots ^_

In console I check this:
```
date
gio  6 lug 2017, 11.02.22, CEST
```
in php.ini I have
```
date.timezone = Europe/Rome
```
That are coherent.

@jtpalmer do you have any idea?

Thank you.

**Comment by jtpalmer** [comment]
@iotaka We've seen this issue before, but haven't found a solution yet.  I would expect that it has something to do with the timezone.  Check your MySQL/MariaDB timezone to see if that matches the others.

**Comment by iotaka** [comment]
Hi @jtpalmer 

as expected it uses the one of the system:

```
SELECT @@global.time_zone, @@session.time_zone;
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| SYSTEM             | SYSTEM              |
+--------------------+---------------------+
```

**Comment by jtpalmer** [comment]
@iotaka we still haven't solved this issue, but have decided to stop using GitHub issues in favor of our ticketing system. Please contact us at ccr-xdmod-help at buffalo.edu for any future support requests.
