### ISSUE TITLE
Ingestion fails after update from MariaDB 10.1.24 to MariaDB 10.2.7

### ISSUE THREAD

**Issue by datakid** [ubccr/xdmod#192]
After upgrade of MariaDB-server, ingestion fails with standard looking data.

## Expected Behavior

Ingestion should work.

## Current Behavior

See this output:

> 2017-07-25 01:00:10 [error] Command returned non-zero value '1': ERROR 1366 (22007) at line 1: Incorrect integer value: '' for column 'wait_time' at row 3 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
> #1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
> #2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
> #3 /usr/bin/xdmod-slurm-helper(209): PDODBMultiIngestor->ingest()
> #4 /usr/bin/xdmod-slurm-helper(21): main()
> #5 {main}, statement: load data local infile '/tmp/shredded_job.data.3306.YJt1OT' replace into table shredded_job fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (date_key,job_id,job_array_index,job_id_raw,job_name,resource_name,queue_name,user_name,uid_number,group_name,gid_number,account_name,pi_name,start_time,end_time,submission_time,eligible_time,exit_code,exit_state,wall_time,wait_time,node_count,cpu_count,cpu_req,mem_req,timelimit,node_list,source_format))
> 2017-07-25 01:00:10 [error] SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'resource_shared_jobs' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/DB/ArrayIngestor.php(74): PDOStatement->execute(Array)
> #1 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(373): ArrayIngestor->ingest()
> #2 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(299): OpenXdmod\DataWarehouseInitializer->ingest(Array, Object(CCR\DB\MySQLDB), Object(CCR\DB\MySQLDB), NULL, NULL)
> #3 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(238): OpenXdmod\DataWarehouseInitializer->ingestAllStaging(NULL, NULL)
> #4 /usr/bin/xdmod-ingestor(227): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
> #5 /usr/bin/xdmod-ingestor(21): main()
> #6 {main}, source_row: ["1",1,1,"Bioinformatics Cluster","fiona","",false,"Australia\/Melbourne"])
> 2017-07-25 01:00:10 [error] SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'resource_shared_jobs' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/DB/ArrayIngestor.php(74): PDOStatement->execute(Array)
> #1 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(373): ArrayIngestor->ingest()
> #2 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(299): OpenXdmod\DataWarehouseInitializer->ingest(Array, Object(CCR\DB\MySQLDB), Object(CCR\DB\MySQLDB), NULL, NULL)
> #3 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(238): OpenXdmod\DataWarehouseInitializer->ingestAllStaging(NULL, NULL)
> #4 /usr/bin/xdmod-ingestor(227): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
> #5 /usr/bin/xdmod-ingestor(21): main()
> #6 {main}, source_row: ["2",1,1,"Bioinformatics Cluster: Rosalind Franklin","rosalind","",false,"Australia\/Melbourne"])
> 2017-07-25 01:00:10 [error] Command returned non-zero value '1': ERROR 1263 (22004) at line 1: Column set to default value; NULL supplied to NOT NULL column 'initial_end_date' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
> #1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
> #2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
> #3 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(373): PDODBMultiIngestor->ingest()
> #4 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(337): OpenXdmod\DataWarehouseInitializer->ingest(Array, Object(CCR\DB\MySQLDB), Object(CCR\DB\MySQLDB), NULL, NULL)
> #5 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(239): OpenXdmod\DataWarehouseInitializer->ingestAllHpcdb(NULL, NULL)
> #6 /usr/bin/xdmod-ingestor(227): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
> #7 /usr/bin/xdmod-ingestor(21): main()
> #8 {main}, statement: load data local infile '/tmp/allocation.data.3306.FGaILu' replace into table allocation fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (id,resource_id,account_id,request_id,principalinvestigator_person_id,fos_id,initial_end_date,base_allocation,remaining_allocation,end_date,end_date_ts,allocation_type_id,charge_number,conversion_factor,xd_su_per_hour,long_name,short_name,order_id))
> 2017-07-25 01:00:13 [error] Command returned non-zero value '1': ERROR 1366 (22007) at line 1: Incorrect integer value: '' for column 'id' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
> #1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
> #2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
> #3 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(373): PDODBMultiIngestor->ingest()
> #4 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(337): OpenXdmod\DataWarehouseInitializer->ingest(Array, Object(CCR\DB\MySQLDB), Object(CCR\DB\MySQLDB), NULL, NULL)
> #5 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(239): OpenXdmod\DataWarehouseInitializer->ingestAllHpcdb(NULL, NULL)
> #6 /usr/bin/xdmod-ingestor(227): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
> #7 /usr/bin/xdmod-ingestor(21): main()
> #8 {main}, statement: load data local infile '/tmp/resourcetype.data.3306.xebIQo' replace into table resourcetype fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (id,abbrev,description))
> 2017-07-25 01:00:14 [error] Command returned non-zero value '1': ERROR 1292 (22007) at line 1: Incorrect datetime value: '1467085329' for column 'ts' at row 1 (stacktrace: #0 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(296): CCR\DB\MySQLHelper::staticExecuteCommand(Array, NULL)
> #1 /usr/share/xdmod/classes/CCR/DB/MySQLHelper.php(243): CCR\DB\MySQLHelper->executeCommand(Array)
> #2 /usr/share/xdmod/classes/DB/PDODBMultiIngestor.php(253): CCR\DB\MySQLHelper->executeStatement('load data local...')
> #3 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(373): PDODBMultiIngestor->ingest()
> #4 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(337): OpenXdmod\DataWarehouseInitializer->ingest(Array, Object(CCR\DB\MySQLDB), Object(CCR\DB\MySQLDB), NULL, NULL)
> #5 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(239): OpenXdmod\DataWarehouseInitializer->ingestAllHpcdb(NULL, NULL)
> #6 /usr/bin/xdmod-ingestor(227): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
> #7 /usr/bin/xdmod-ingestor(21): main()
> #8 {main}, statement: load data local infile '/tmp/systemaccount.data.3306.TuWW8p' replace into table systemaccount fields terminated by 0x1e optionally enclosed by 0x1f lines terminated by 0x1d (id,person_id,resource_id,username,ts,uid))

## Context
XDMoD no longer shows proper output ("no data available") in the web GUI; am getting errors from teh CRON job that injests at midnight.

Has been working happily for the previous year or so.

## Your Environment

* Version used: 6.6.0
* Environment name and version: 
[root@server ~]# xdmod-check-config 
XDMoD 6.6.0

Required prerequisites

 OK       MySQL command line client installed
 OK       PHP version must be at least 5.3.0
 OK       PHP Data Objects (PDO) extension installed
 OK       MySQL PDO driver installed
 OK       PHP GD extension installed
 OK       PHP GMP extension installed
 OK       PHP Mcrypt extension installed
 OK       PHP cURL extension installed
 OK       PHP DOM extension installed
 OK       PHP XMLWriter extension installed
 OK       PHP PEAR Log class installed
 OK       PHP MDB2 class installed
 OK       PHP MDB2 MySQL driver installed
 OK       PHP JSON extension installed
 OK       PHP session support installed
 OK       PHP PCRE extension installed
 OK       PHP Timezone set
 OK       Java executable configured
 OK       Javac executable configured
 OK       PhantomJS configured
 OK       sendmail executable installed

* Operating system and version:  CentOS 7 Server (headless), MariaDB 10.2.7 from MariaDB repos

**Comment by jtpalmer** [comment]
@datakid New versions of MySQL and MariaDB have changed their default `sql_mode`.  You can verify this with this query:

```sql
SHOW VARIABLES LIKE 'sql_mode';
```

Set `sql_mode=''` in your configuration if it is not already the empty string.  Let us know if this does not resolve the issue.

**Comment by plessbd** [comment]
closing due to no user response
