### ISSUE TITLE
Dual Appointments in Hierarchy Feature

### ISSUE THREAD

**Issue by jgao154** [ubccr/xdmod#223]
if there is a possible way to show that one PI has dual appointments to different departments in the Hierarchy features? 
For Example: Professor A belongs to a primary department B and secondary department C, is there a way to appoint professor A's usage to both departments?

Currently we have a two level hierarchy settings with PI groups linked directly to Departments and then to Colleges. 

​

**Comment by jtpalmer** [comment]
Hi @jgao154 , please excuse me for not responding earlier.  What you're looking for is currently not possible.  Please contact us at ccr-xdmod-help at buffalo.edu for any future support requests.
