### ISSUE TITLE
Federated login using iframe (and failing)

### ISSUE THREAD

**Issue by Elwell** [ubccr/xdmod#228]
Hi, 
I've installed xdmod-6.6.0-1.0.el7.centos.noarch and set it up to use our SSO (also based on SimpleSamlPHP as IdP on another host, however the login box doesn't properly display

I see the "Login with your Federated account" dialog on the LHS of the popup window (screenshot attached)

<img width="1009" alt="screen shot 2017-08-29 at 3 39 29 pm" src="https://user-images.githubusercontent.com/209107/29809937-99c5c788-8cd0-11e7-8f8c-d92dc2f12e7c.png">

but clicking on that just shows a blank page. (opening link in new tab works OK though) - it looks like this is caused by the iframe  - Chrome inspector shows
```
Refused to display 'https://mackenzie.pawsey.org.au/simplesaml/module.php/core/loginuserpass.php?AuthState=_9be2eaea1c3bbfceade51304752288d8e00d5408cb%3Ahttps%3A%2F%2Fmackenzie.pawsey.org.au%2Fsimplesaml%2Fsaml2%2Fidp%2FSSOService.php%3Fspentityid%3Dhttps%253A%252F%252Fxdmod.pawsey.org.au%252Fsimplesaml%252Fmodule.php%252Fsaml%252Fsp%252Fmetadata.php%252Fdefault-sp%26cookieTime%3D1503992893%26RelayState%3Dhttps%253A%252F%252Fxdmod.pawsey.org.au%252Fgui%252Fgeneral%252Flogin.php' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
mackenzie.pawsey.org.au/simplesaml/module.php/core/loginuserpass.php?AuthState=_9be2eaea1c3bbfceade51304752288d8e00d5408cb%3Ahttps%3A%2F%2Fmackenzie.pawsey.org.au%2Fsimplesaml%2Fsaml2%2Fidp%2FSSOService.php%3Fspentityid%3Dhttps%253A%252F%252Fxdmod.pawsey.org.au%252Fsimplesaml%252Fmodule.php%252Fsaml%252Fsp%252Fmetadata.php%252Fdefault-sp%26cookieTime%3D1503992893%26RelayState%3Dhttps%253A%252F%252Fxdmod.pawsey.org.au%252Fgui%252Fgeneral%252Flogin.php Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE

```

Can the use of iframe(s) be dropped for this? I'm reluctant to alter the allow origin settings on our servers.

Looks like CCR.js calls gui/general/login.php in a frame

**Comment by plessbd** [comment]
see: https://github.com/ubccr/xdmod/pull/225

We are working on that right now
