### ISSUE TITLE
install file missing?

### ISSUE THREAD

**Issue by mkgilbert** [ubccr/xdmod#23]
I just downloaded and extracted xdmod-6.5.0 and don't see an install file. The README points me to the install instructions here: http://open.xdmod.org/install-source.html, but those presuppose an `install` file.

**Comment by mkgilbert** [comment]
So the tar.gz that's listed under the Releases tab is complete and has the install file, whereas the tar.gz listed under the Tags tab is missing some things.

**Comment by jtpalmer** [comment]
The downloads in the Tags tab only contain the code directly from the GitHub repository.  There is a [build process](https://github.com/ubccr/xdmod#building) that you need to use to create the release tar.gz that contains the `install` script.   As you already noted, the Releases tab contains the tar.gz files you're looking for.  Definitely confusing, so we'll have to improve the documentation.

**Comment by mkgilbert** [comment]
No worries, I just wasn't sure if it was intentional. Thank you for the response!
