### ISSUE TITLE
How to get Slurm gres and tres fields to show up?

### ISSUE THREAD

**Issue by mkgilbert** [ubccr/xdmod#51]
I recently upgraded xdmod to version 6.5.0 and am trying to get the new available fields "req_gres" and "req_tres" to show up in the web interface, but am at a loss as to how to accomplish it.

## Expected Behavior
I performed the upgrade successfully (the website is listing the new version) and have been successfully ingesting slurm data in the upgraded install for over a week. I was under the impression these gres and tres fields might automatically get populated on the website.

## Current Behavior
Currently, I am not seeing any place on the website to access these values. I have also examined the database and found that the shredded_job_slurm table has req_tres and req_gres fields, whereas the hpcdb_jobs table does not:

![image](https://cloud.githubusercontent.com/assets/10564849/22754999/9fbaf6de-edfe-11e6-8f19-2bc24ff14a80.png)

![image](https://cloud.githubusercontent.com/assets/10564849/22755012/a8b29e54-edfe-11e6-8739-ddf135dd2414.png)

## Your Environment

* Version used: 6.5.0
* Software: MySQL 5.1.73, Slurm 16.05.6, 
* Operating system and version: CentOS 6.8
* Unfortunately our project is accessible only via our domain.

Thank you!

**Comment by smgallo** [comment]
Hi @mkgilbert, we currently have the ability to store the treg/gres fields but do not have a mechanism available at the moment to display them. These were added so that a user could track the information and make use of it outside of XDMoD. We will evaluate access via the UI sometime later this year.

**Comment by mkgilbert** [comment]
Ahh I see. Thank you for the response!
