### ISSUE TITLE
XD-MoD API ??

### ISSUE THREAD

**Issue by dspatil7768** [ubccr/xdmod#70]
Hello, I'm new to  XD-MOD. I have installed XD-MOD for monitoring Slurm and Torque for testing purpose. So my question is how can we use the charts like Pie and graphs on another website so that it will be more interactive. Can we use any API or does XD-MOD provide any type of such interface?
Thank you,

**Comment by smgallo** [comment]
Hello, we do not currently have a well-defined API for exporting the images from XDMoD. That being said, any chart available on the public page (that does not require login) can be accessed directly via a url. You can view a graph in the Usage Tab and customize the time period and display parameters to your liking and, using browser developer tools such as Firebug, find the url including parameters that was used to get that chart. Add the parameters `&inline=y&format=png` to that url to export the image.

For example, the following url will export a PNG continaing the Total CPU Hours for 2017Q1 (replace "my.xdmod" with the host for your own instance:

https://my.xdmod/controllers/user_interface.php?aggregation_unit=Auto&combine_type=stack&controller_module=user_interface&dataset_type=timeseries&display_type=line&end_date=2017-03-31&font_size=3&group_by=none&height=1030&hide_tooltip=false&interactive_elements=y&legend_type=bottom_center&limit=10&log_scale=n&offset=0&operation=get_charts&public_user=true&query_group=tg_usage&realm=Jobs&scale=1&show_aggregate_labels=n&show_error_bars=n&show_error_labels=n&show_guide_lines=y&show_title=y&show_trend_line=n&start_date=2017-01-01&statistic=total_cpu_hours&thumbnail=n&timeframe_label=Previous%20month&width=1267&inline=y&format=png

**Comment by dspatil7768** [comment]
Ok thank you☺️
