### ISSUE TITLE
[ xdmod-6.5.0 ; Centos 7.2.1511 ] xdmod-shredder -f pbs

### ISSUE THREAD

**Issue by dspatil7768** [ubccr/xdmod#72]
Hello, I have installed 6.5.0 of xdmod. Now I have one resource i.e. Torque scheduler. Previously it was shredding for every job but I don't know now it's showing shredded zero files and shredded zero records for every job that I'm submitting.

`[root@n1 ~]# xdmod-shredder -f pbs -d /opt/PBS/server_priv/accounting/ -r CDAC-2`

Output:

`2017-03-15 18:59:36 [notice] xdmod-shredder start (process_start_time: 2017-03-15 18:59:36)
2017-03-15 18:59:36 [notice] Shredding directory '/opt/PBS/server_priv/accounting/'
2017-03-15 18:59:36 [notice] Shredded 0 files
2017-03-15 18:59:36 [notice] Shredded 0 records total
2017-03-15 18:59:36 [notice] Done shredding files
2017-03-15 18:59:36 [notice] Normalizing data
2017-03-15 18:59:36 [notice] Finished ingestion (class: PDODBMultiIngestor, start_time: 1489584576.1803, end_time: 1489584576.1925, records_examined: 0, records_loaded: 0)
2017-03-15 18:59:36 [notice] Done normalizing data
2017-03-15 18:59:36 [notice] xdmod-shredder end (process_end_time: 2017-03-15 18:59:36)`

It is given on XDMoD site that:

> The log file for the current day will be ignored (along with any files that correspond to future dates). This is intended to prevent the shredding of partial log files. If the database is empty all files that meet the above constraints will be shredded. If there is data in the database, only files dated after the date of the most recent job will be shredded.

suggest if I'm going wrong
Thank you!

**Comment by dspatil7768** [comment]
Other one alternative is to specify the file directly:
` xdmod-shredder -f pbs -i /opt/PBS/server_priv/accounting/20170322 -r CDAC-2`
But using `-d` it will be more simple rather than `-i`.

**Comment by dspatil7768** [comment]
Using `-i` parameter what I did is that I wrote script in python:

`import os` 
 `import time`
`data = os.listdir("/opt/PBS/server_priv/accounting")`
`comp = time.strftime("%Y%m%d")`
`for filename in data:`
    `if filename == comp:`
        `shredder="xdmod-shredder -f pbs -i /opt/PBS/server_priv/accounting/"+filename+" -r CDAC-2"`
        `os.system(shredder)`
        `ingestor="xdmod-ingestor"`
        `os.system(ingestor)`
`
And using Crontab I got result.

**Comment by jtpalmer** [comment]
Was there already job data in your database when using the `-d` option?  I don't think you're doing anything wrong.  Try running the `xdmod-shredder` command with either the verbose (`-v`) or debug (`--debug`) option to get a better idea of what is going on.

**Comment by dspatil7768** [comment]
Yes, I have data in my database. I tried running `xdmod-shredder` with `-v` also. But when I run jobs and again execute using `-d` it's showing `Shredded 0 files`

**Comment by jtpalmer** [comment]
This sounds like it's working as intended.  This is what that documentation you quoted was referencing.  Since you already have data, no files with earlier dates will be shredded.
