### ISSUE TITLE
[ XD-MoD 6.5.0 ] Dynamic webpage? 

### ISSUE THREAD

**Issue by dspatil7768** [ubccr/xdmod#99]
Is there any way to dynamically refresh `XDMoD` webpage?

**Comment by jtpalmer** [comment]
I'm not sure what you mean.  What are you trying to refresh and how do you want to do so?

**Comment by dspatil7768** [comment]
I mean to say that we need to always refresh our browser to see graphs and pie charts. So is there any way that it could be done automatically with out pressing refresh button.

**Comment by jtpalmer** [comment]
@dspatil7768 please excuse my delay in responding.  What you are looking for is currently not possible. Please contact us at ccr-xdmod-help at buffalo.edu for any future support requests.
